#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONF_DIR="$PROJECT_DIR/conf/doris"

TAG="${1:-}"
if [ -z "$TAG" ]; then
    TAG=$(grep -A4 'observability:' "$PROJECT_DIR/VERSIONS.yaml" 2>/dev/null \
        | grep 'version:' | head -1 | awk '{print $NF}')
fi
if [ -z "$TAG" ]; then
    echo "Usage: $0 <tag>  (e.g. $0 v0.0.1)"
    exit 1
fi

REPO="rainway-ai-gateway/ai-gateway-observability"

DORIS_DATABASE="bfe_observability"
INIT_PARTITION_DATE=$(date -v-1d +%Y-%m-%d 2>/dev/null || date -d yesterday +%Y-%m-%d)
KAFKA_TOPIC="bfe_ai_log"
KAFKA_GROUP_ID="doris_bfe_ai_log"
KAFKA_CLIENT_ID="doris_bfe_ai_log"
DOCKER_KAFKA_BROKER="kafka.ai-gateway-system:9092"
K8S_KAFKA_BROKER="kafka.ai-gateway-system.svc.cluster.local:9092"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

URL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
echo "Downloading ${URL} ..."
curl -sL "$URL" | tar xz -C "$TMPDIR"

DIR_NAME="${TAG#v}"
SRC_DIR="$TMPDIR/ai-gateway-observability-${DIR_NAME}"
if [ ! -d "$SRC_DIR" ]; then
    echo "ERROR: extracted directory not found at $SRC_DIR"
    exit 1
fi

echo "Source : $SRC_DIR"
echo "Target : $CONF_DIR"
echo ""

render_sql() {
    local src="$1" dst="$2" kafka_broker="$3"
    sed \
        -e "s|\${DORIS_DATABASE}|${DORIS_DATABASE}|g" \
        -e "s|\${INIT_PARTITION_DATE}|${INIT_PARTITION_DATE}|g" \
        -e "s|\${KAFKA_BROKER_LIST}|${kafka_broker}|g" \
        -e "s|\${KAFKA_TOPIC}|${KAFKA_TOPIC}|g" \
        -e "s|\${KAFKA_GROUP_ID}|${KAFKA_GROUP_ID}|g" \
        -e "s|\${KAFKA_CLIENT_ID}|${KAFKA_CLIENT_ID}|g" \
        "$src" > "$dst"
}

FILE_MAP=(
    "bfe_observability.sql:01_create_database.sql"
    "bfe_ai_request_log.sql:02_create_detail_table.sql"
    "bfe_ai_log_load_routine.sql:03_create_routine_load.sql"
    "bfe_ai_metrics_1m.sql:04_create_aggregate_table.sql"
    "bfe_ai_metrics_1m_job.sql:05_create_insert_job.sql"
)

echo "Rendering Docker Compose SQL (Kafka: ${DOCKER_KAFKA_BROKER}) ..."
for entry in "${FILE_MAP[@]}"; do
    src_name="${entry%%:*}"
    dst_name="${entry##*:}"
    render_sql "$SRC_DIR/doris/sqls/${src_name}" "$CONF_DIR/${dst_name}" "$DOCKER_KAFKA_BROKER"
    echo "  ${dst_name}"
done

# --- K8s ConfigMap ---
K8S_CONFIGMAP="$PROJECT_DIR/kubernetes/deploy/doris-configmap.yaml"
K8S_TMP="$TMPDIR/k8s-sql"
mkdir -p "$K8S_TMP"

echo ""
echo "Rendering K8s SQL (Kafka: ${K8S_KAFKA_BROKER}) ..."
for entry in "${FILE_MAP[@]}"; do
    src_name="${entry%%:*}"
    dst_name="${entry##*:}"
    render_sql "$SRC_DIR/doris/sqls/${src_name}" "$K8S_TMP/${dst_name}" "$K8S_KAFKA_BROKER"
done

{
    cat <<'HEADER'
# Copyright(c) 2024 Beijing Yingfei Networks Technology Co.Ltd. All rights reserved.
# Licensed under the Apache License, Version 2.0.

# Auto-generated by scripts/sync-doris.sh — do not edit manually.
# Regenerate: make sync-doris
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doris-init-sql
  namespace: default
data:
HEADER
    for entry in "${FILE_MAP[@]}"; do
        dst_name="${entry##*:}"
        echo "  ${dst_name}: |"
        sed 's/^/    /' "$K8S_TMP/${dst_name}"
        echo ""
    done
} > "$K8S_CONFIGMAP"

echo ""
echo "Done (tag ${TAG}). Updated:"
echo "  conf/doris/01_create_database.sql"
echo "  conf/doris/02_create_detail_table.sql"
echo "  conf/doris/03_create_routine_load.sql"
echo "  conf/doris/04_create_aggregate_table.sql"
echo "  conf/doris/05_create_insert_job.sql"
echo "  kubernetes/deploy/doris-configmap.yaml"
