#!/usr/bin/env bash
# ============================================================
# Sync Grafana config from ai-gateway-observability
# ============================================================
# Downloads the specified tag, renders templates with Docker
# Compose defaults, and writes to conf/grafana/.
#
# Usage:
#   bash scripts/sync-grafana.sh v0.0.1
#   bash scripts/sync-grafana.sh          # reads version from VERSIONS.yaml
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONF_DIR="$PROJECT_DIR/conf/grafana"

# --- Resolve tag ---
TAG="${1:-}"
if [ -z "$TAG" ]; then
    TAG=$(grep -A4 'observability:' "$PROJECT_DIR/VERSIONS.yaml" 2>/dev/null \
        | grep 'version:' | head -1 | awk '{print $NF}')
fi
if [ -z "$TAG" ]; then
    echo "Usage: $0 <tag>  (e.g. $0 v0.0.1)"
    exit 1
fi

REPO="rainway-ai-gateway/ai-gateway-observability"

# Docker Compose defaults (match docker-compose.yml service names)
DATASOURCE_NAME="Doris"
DATASOURCE_UID="doris"
DORIS_HOST="doris-fe.ai-gateway-system"
DORIS_PORT="9030"
DORIS_DATABASE="bfe_observability"
DORIS_USER="root"
DORIS_PASSWORD=""

# --- Download ---
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

URL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
echo "Downloading ${URL} ..."
curl -sL "$URL" | tar xz -C "$TMPDIR"

# GitHub strips leading 'v' from directory name
DIR_NAME="${TAG#v}"
SRC_DIR="$TMPDIR/ai-gateway-observability-${DIR_NAME}"
if [ ! -d "$SRC_DIR" ]; then
    echo "ERROR: extracted directory not found at $SRC_DIR"
    exit 1
fi

echo "Source : $SRC_DIR"
echo "Target : $CONF_DIR"
echo ""

# --- 1. Datasource ---
echo "Rendering provisioning/datasources/doris.yaml ..."
sed \
    -e "s|\${DATASOURCE_NAME}|${DATASOURCE_NAME}|g" \
    -e "s|\${DATASOURCE_UID}|${DATASOURCE_UID}|g" \
    -e "s|\${DORIS_HOST}|${DORIS_HOST}|g" \
    -e "s|\${DORIS_PORT}|${DORIS_PORT}|g" \
    -e "s|\${DORIS_DATABASE}|${DORIS_DATABASE}|g" \
    -e "s|\${DORIS_USER}|${DORIS_USER}|g" \
    -e "s|\${DORIS_PASSWORD}|${DORIS_PASSWORD}|g" \
    "$SRC_DIR/grafana/datasources/doris.yaml" \
    > "$CONF_DIR/provisioning/datasources/doris.yaml"

# --- 2. Dashboard JSON ---
echo "Rendering dashboards/bfe-ai-gateway-observability.json ..."
sed \
    -e "s|\${DS_DORIS}|${DATASOURCE_UID}|g" \
    -e "s|\${DATASOURCE_NAME}|${DATASOURCE_NAME}|g" \
    -e "s|\${DORIS_DATABASE}|${DORIS_DATABASE}|g" \
    "$SRC_DIR/grafana/dashboards/bfe-ai-gateway-observability.json" \
    > "$CONF_DIR/dashboards/bfe-ai-gateway-observability.json"

# --- 3. Dashboard provider — NOT touched (bfe_ai.yaml preserved) ---

# --- 4. K8s ConfigMap ---
K8S_CONFIGMAP="$PROJECT_DIR/kubernetes/deploy/grafana-configmap.yaml"
K8S_DORIS_HOST="doris-fe.default.svc.cluster.local"

echo ""
echo "Generating K8s ConfigMap ..."

# Render K8s-specific datasource (different DORIS_HOST)
K8S_DATASOURCE="$TMPDIR/k8s-datasource.yaml"
sed \
    -e "s|\${DATASOURCE_NAME}|${DATASOURCE_NAME}|g" \
    -e "s|\${DATASOURCE_UID}|${DATASOURCE_UID}|g" \
    -e "s|\${DORIS_HOST}|${K8S_DORIS_HOST}|g" \
    -e "s|\${DORIS_PORT}|${DORIS_PORT}|g" \
    -e "s|\${DORIS_DATABASE}|${DORIS_DATABASE}|g" \
    -e "s|\${DORIS_USER}|${DORIS_USER}|g" \
    -e "s|\${DORIS_PASSWORD}|${DORIS_PASSWORD}|g" \
    "$SRC_DIR/grafana/datasources/doris.yaml" \
    > "$K8S_DATASOURCE"

{
    cat <<'HEADER'
# Copyright(c) 2024 Beijing Yingfei Networks Technology Co.Ltd. All rights reserved.
# Licensed under the Apache License, Version 2.0.

# Auto-generated by scripts/sync-grafana.sh — do not edit manually.
# Regenerate: make sync-grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: default
data:
  datasource.yaml: |
HEADER
    sed 's/^/    /' "$K8S_DATASOURCE"
    echo ""
    echo "  dashboard-provider.yaml: |"
    sed 's/^/    /' "$CONF_DIR/provisioning/dashboards/bfe_ai.yaml"
    echo ""
    echo "  dashboard.json: |"
    sed 's/^/    /' "$CONF_DIR/dashboards/bfe-ai-gateway-observability.json"
} > "$K8S_CONFIGMAP"

echo ""
echo "Done (tag ${TAG}). Updated:"
echo "  conf/grafana/provisioning/datasources/doris.yaml"
echo "  conf/grafana/dashboards/bfe-ai-gateway-observability.json"
echo "  conf/grafana/provisioning/dashboards/bfe_ai.yaml (unchanged)"
echo "  kubernetes/deploy/grafana-configmap.yaml"
